Update dotfiles

diff --git a/bin/grimvshot b/bin/grimvshot
--- a/bin/grimvshot
+++ b/bin/grimvshot
@@ -1,17 +1,16 @@
 #!/bin/bash
-#
-# Make a screenshot of either [focused] window, arbitrary rectangular area or a whole output.
 set -eo pipefail
+
 if (( $(pgrep -x grimvshot | wc -l) > 2 )); then
 	# Prevent running it multiple times
 	exit 0
 fi
 
-usage () {
-	echo \
-		"Usage: $(basename "$0") [--notify] [--cursor] [--swaynag] [--copy]" \
-		"[-o|--file <FILE>] [--output=<OUTPUT>]" \
-		"[--active|--area|--screen|--window]" >&2
+usage() {
+	echo -e \
+		"Usage:\n\t$(basename "$0") [--notify] [--cursor] [--swaynag] [--copy]" \
+		"[-o <FILE>|--file=<FILE>] [--output=<OUTPUT>]" \
+		"--active|--area|--screen|--window" >&2
 	exit 1
 }
 
@@ -21,6 +20,14 @@ get_focused_output() {
 
 get_default_savefile() {
 	echo "$(xdg-user-dir PICTURES)/grim-$(date -Ins).png"
+}
+
+check_required() {
+	local required=(swaymsg xdg-user-dir imv grim slurp swappy notify-send)
+	if ! hash "${required[@]}" &>/dev/null; then
+		echo -e "Script requires the following programs to be installed:\n\t${required[*]}" >&2
+		exit 1
+	fi
 }
 
 optstr=$(getopt -o ho: -l help,notify,swaynag,cursor,copy,file:,output:,active,area,screen,window,focused -- "$@")
@@ -43,13 +50,15 @@ done
 
 [[ -z $ACTION ]] && usage
 
+check_required
+
 ALL_NODES='recurse(.nodes[], .floating_nodes[])'
 TO_RECT='"\(.rect.x),\(.rect.y - .deco_rect.height) \(.rect.width)x\(.rect.height + .deco_rect.height)"'
 
 case $ACTION in
 	--area)
 		bake="$(mktemp /tmp/grimvshot-XXXXXX.png)"
-		grim -c -o "$(get_focused_output)" "$bake"
+		grim -o "$(get_focused_output)" "$bake"
 		imv -f "$bake" &
 		IMV_PID=$!
 		if ! GEOM="$(slurp)"; then
@@ -60,7 +69,7 @@ case $ACTION in
 		;;
 	--window)
 		bake="$(mktemp /tmp/grimvshot-XXXXXX.png)"
-		grim -c -o "$(get_focused_output)" "$bake"
+		grim -o "$(get_focused_output)" "$bake"
 		imv -f "$bake" &
 		IMV_PID=$!
 		if ! GEOM=$(swaymsg -t get_tree | jq -r "$ALL_NODES | select(.pid? and .visible?) | $TO_RECT" | slurp); then
@@ -77,19 +86,21 @@ if [[ -n $bake ]]; then
 	rm "$bake"
 fi
 
-[[ -n $OUTPUT ]] && args+=(-o "$OUTPUT")
-[[ -n $GEOM ]] && args+=(-g "$GEOM")
+grim_args=()
+[[ -n $OUTPUT ]] && grim_args+=(-o "$OUTPUT")
+[[ -n $GEOM ]] && grim_args+=(-g "$GEOM")
+[[ $WITH_CURSOR == 1 ]] && grim_args+=(-c)
 
 if [[ -n $RUN_SWAYNAG ]]; then
 	TMPFILE="$(mktemp /tmp/grimvshot-XXXXXX.png)"
 	FILE="$(get_default_savefile)"
-	grim "${args[@]}" "$TMPFILE"
+	grim "${grim_args[@]}" "$TMPFILE"
 elif [[ -n $COPY ]]; then
-	grim "${args[@]}" - | wl-copy
+	grim "${grim_args[@]}" - | wl-copy
 	echo "Screenshot copied to clipboard"
 else
 	FILE=${FILE:-$(get_default_savefile)}
-	grim "${args[@]}" "$FILE"
+	grim "${grim_args[@]}" "$FILE"
 	echo "Screenshot saved to $FILE"
 fi
 
